name: Daily Word Generation

on:
  schedule:
    # Run at midnight UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual triggering

# Use GitHub's built-in token for authentication
permissions:
  contents: write

jobs:
  generate-and-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Generate daily word
        run: python scripts/generate_daily_word.py
          
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/data/daily.json public/data/history.json
          git commit -m "Update daily word for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
