name: Daily Word Generation

on:
  schedule:
    # Run at midnight UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual triggering

# Use GitHub's built-in token for authentication
permissions:
  contents: write

jobs:
  generate-and-upload:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Generate daily word
        run: python scripts/generate_daily_word.py
        
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Vercel Blob dependencies
        run: npm install @vercel/blob
          
      - name: Upload to Vercel Blob Storage
        env:
          BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
        run: |
          echo "Uploading daily word data to Vercel Blob Storage..."
          node scripts/upload-to-blob.js
          
      - name: Commit history file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/data/history.json
          git commit -m "Update history for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
          
      - name: Notify Vercel of changes
        run: |
          echo "Notifying Vercel of changes to trigger a deployment..."
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_${{ secrets.VERCEL_PROJECT_ID }}/VGPxMbwcfcHYrUJQWHgBTM9p" \
            -H "Content-Type: application/json"
