name: Daily Word Generation

on:
  schedule:
    # Run at midnight UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-daily-word:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Generate daily word
        run: |
          python scripts/generate_daily_word.py
          
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          # Install Vercel CLI
          npm install -g vercel
          
          # Create a temporary directory for the deployment
          mkdir -p deploy/public/data
          
          # Copy the generated daily.json file
          cp public/data/daily.json deploy/public/data/
          cp public/data/history.json deploy/public/data/
          
          # Deploy only the data files to Vercel
          cd deploy
          vercel --token $VERCEL_TOKEN --prod --yes
